version: 2
updates:
  # --- 1. GitHub Actions ---
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"

  # --- 2. Backend (FastAPI / uv) ---
  # Dependabot treats uv as pip for now
  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"

  # --- 3. Frontend (React / pnpm) ---
  - package-ecosystem: "npm"
    directory: "/frontend/app"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
