version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodatabase
    ports:
      - "27012:27017"
    volumes:
      - mongodb_data:/data/db
    # networks:
    #   - fastapi_network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6372:6379"
    # networks:
    #   - fastapi_network
  fake-smtp:
    image: haravich/fake-smtp-server
    container_name: fake_smtp
    ports:
      - "1023:1025"
      - "1083:1080"
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    # networks:
    #   - fastapi_network
  

volumes:
  mongodb_data:
  redis_data:
  caddy_data:
  caddy_config:

# networks:
#   fastapi_network: